version: "3.8"

services:
  web:
    container_name: web
    image: jointakahe/takahe:0.11.0
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8001"
    volumes:
      - ./static/css/mes.css:/takahe/static/css/mes.css
      - ./media:/media

  worker:
    container_name: stator
    image: jointakahe/takahe:0.11.0
    command: python3 manage.py runstator
    env_file: .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${PGNAME}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}

volumes:
  postgres_data:
